### ISSUE TITLE
com.ticketmaster.purchase.exception.TMFragmentFactoryNotFound: Please use TMPurchaseFragmentFactory

### ISSUE THREAD

**Issue by ohsnapitscolin** [ticketmaster/ReactNative-TicketmasterDemoIntegration#9]
Hey all,

When running through the purchase from on sample app, and clicking "Next", I'm presented with the following error when trying to navigate to navigate to the cart:

```
E/DevLauncher: DevLauncher tries to handle uncaught exception.
    com.ticketmaster.purchase.exception.TMFragmentFactoryNotFound: Please use TMPurchaseFragmentFactory
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseFragment$setupNavigationObserver$1.invoke(PurchaseFragment.kt:319)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseFragment$setupNavigationObserver$1.invoke(PurchaseFragment.kt:298)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseFragment$sam$androidx_lifecycle_Observer$0.onChanged(Unknown Source:2)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseViewModel.openCheckout(PurchaseViewModel.kt:469)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseViewModel.setAccessToken(PurchaseViewModel.kt:408)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseViewModel.access$setAccessToken(PurchaseViewModel.kt:63)
        at com.ticketmaster.purchase.internal.ui.ticket.PurchaseViewModel$shouldHandleUrl$handleUrlForCheckout$1$1.invokeSuspend(PurchaseViewModel.kt:371)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@88d29d1, Dispatchers.Main.immediate]
```

No custom code or changes here, getting this in the cloned repo with any modifications.

**Comment by TakaGoto** [comment]
hey @ohsnapitscolin can you tell me more about the steps taken to get to the error.
* did you go through prepurchase or purchase tab
* were you logged in already when going through the flow

**Comment by ohsnapitscolin** [comment]
Hey @TakaGoto, here's a video of the crash - I was logged in at the time, and using the Purchase flow:
https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/assets/5816480/59535fa9-3f74-4be7-9068-a5ac62933a34

I actually added some additional info to https://github.com/ticketmaster/Android-TicketsDemoApp/issues/6 (happy to consolidate these tickets), but it seems like there's an issue using Purchase as a Fragment instead of as an Activity.

Also just a note I had to change the height in `manuallyLayoutChildren` method of the `PurchaseViewManager` to actually be able to see the "Next" button.

**Comment by TakaGoto** [comment]
thanks @ohsnapitscolin i have a PR up to fix the underlying issue. though you might encounter another error in the flow, currently looking into it.

https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/pull/10

**Comment by ohsnapitscolin** [comment]
> thanks @ohsnapitscolin i have a PR up to fix the underlying issue. though you might encounter another error in the flow, currently looking into it.
> 
> #10

Thanks @TakaGoto! I'll give it a try and let you know if I run into any issues.

**Comment by ohsnapitscolin** [comment]
Hey @TakaGoto, just tested this out. Looking better, but still running into some problems:
1. When transitioning to checkout I'm now getting an error popup, however the transition appears to be successful.
2. The checkout activity appears to be its own activity, not a fragment, which means it's not adhering the boundaries set in the PurchaseViewManager (the navigation bar is overlapping with the app safe area insets). There is there any way to handle this?

https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/assets/5816480/090c3e95-beeb-4697-b315-867f7b67a263

**Comment by ohsnapitscolin** [comment]
Hey @TakaGoto just wanted to give a quick bump on this to see if you have any solutions for the issue above.

**Comment by TakaGoto** [comment]
@ohsnapitscolin sorry for the delay, we have a fix for this but its not released yet. you can try it out with a snapshot version of this:

`com.ticketmaster.retail:purchase:ICCPAPP-1437-03-SNAPSHOT`

just know you'll have to update that in the future. i can try to remember to ping you when its released.

**Comment by TakaGoto** [comment]
closing this issue since we have switched from fragments to activities

**Comment by ohsnapitscolin** [comment]
Hey @TakaGoto the activities work great! Still running into an issue when going to checkout though. I filed https://github.com/ticketmaster/ReactNative-TicketmasterDemoIntegration/issues/14 to track that instead.
